version: '3.1'
services:
  bitbucket:
    image: atlassian/bitbucket
    container_name: "bitbucket"
    depends_on:
      - database
    ports:
      - "9902:9902"
    networks:
      - kolschnet
    restart: always
    volumes:
      - "./config:/var/atlassian/application-data/bitbucket"
    environment:
      BITBUCKET_PROXY_NAME: "bitbucket.internal"
      BITBUCKET_PROXY_PORT: "80"
      JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      JDBC_URL: "jdbc:mysql://database:3306/?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin"
      JDBC_USER: root
      JDBC_PASSWORD: KdGxvQYJZaPA9gUaXB2s
  database:
    image: mysql:8.0
    container_name: "atlassian-db"
    ports:
      - "33000:3306"
    networks:
      - kolschnet
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: KdGxvQYJZaPA9gUaXB2s
networks:
  kolschnet:
    external:
      name: kolschnet