# Atlassian ist keine Option, aufgrund der verursachten kosten

version: '3.1'
services:
  bitbucket:
    image: atlassian/bitbucket
    container_name: "bitbucket"
    depends_on:
      - database
    ports:
      - "9902:9902"
    networks:
      - kolschnet
    restart: always
    volumes:
      - "./config:/var/atlassian/application-data/bitbucket"
    environment:
      BITBUCKET_PROXY_NAME: "bitbucket.internal"
      BITBUCKET_PROXY_PORT: "80"
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: "jdbc:postgresql://database:5432/?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin"
      JDBC_USER: root
      JDBC_PASSWORD: KdGxvQYJZaPA9gUaXB2s
  database:
    image: postgres:latest
    container_name: "atlassian-db"
    ports:
      - "33000:5432"
    networks:
      - kolschnet
    restart: always
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: KdGxvQYJZaPA9gUaXB2s
networks:
  kolschnet:
    external:
      name: kolschnet