version: '3.1'
services:
    spring:
        build:
            dockerfile: ./docker/Dockerfile-Spring
            context: .
        ports:
            - "9901:9900"
        container_name: "helloworld"
        networks:
            - kolschnet
        restart: always

networks:
    kolschnet:
        external:
            name: kolschnet