version: '3.1'
services:
    spring:
        build:
            dockerfile: ./docker/Dockerfile-Spring
            context: .
        ports:
            - "9901:9900"
        container_name: "testserver"
        restart: always
        networks:
            backend:
                aliases:
                    - backend
            kolschnet:
                aliases:
                    - backend

networks:
    backend:
        driver: bridge
        driver_opts:
            com.docker.network.internal: "true"
        ipam:
            driver: default
            config:
                - subnet: 10.94.1.0/29
    kolschnet:
        external:
            name: kolschnet