version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: "minecraft"
    ports:
      - "9901:25565"
    environment:
      EULA: "TRUE"
    networks:
      - kolschnet
    tty: true
    stdin_open: true
    restart: always


networks:
  kolschnet:
    external:
      name: kolschnet
