version: "3.8"

minecraft:
  image: itzg/minecraft-server
  container_name: "minecraft"

  ports:
    - "25565:25565"

  environment:
    EULA: "TRUE"
  networks:
    - kolschnet

  tty: true
  stdin_open: true
  restart: always


networks:
  kolschnet:
    external:
      name: kolschnet
