version: "3.6"
services:
    gitlab:
        image: gitlab/gitlab-ee:latest
        container_name: "gitlab"
        ports:
            - "2201:22"
            - "9900:80"
            # - "443:443"
        volumes:
            - $GITLAB_HOME/data:/var/opt/gitlab
            - $GITLAB_HOME/logs:/var/log/gitlab
            - $GITLAB_HOME/config:/etc/gitlab
        # hostname: 'gitlab.kolschnet.de'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                gitlab_rails['gitlab_shell_ssh_port'] = 2201
            #GITLAB_OMNIBUS_CONFIG: |
            #    external_url 'gitlab.example.com'
        networks:
            - kolschnet
networks:
    kolschnet:
        external:
            name: kolschnet