version: '3.1'
services:
    reverseproxy:
        image: nginx:1.21
        container_name: "reverseproxy"
        ports:
            - "80:80"
            - "25565:25565"
        networks:
            - kolschnet
        restart: always
        volumes:
            - "./config:/etc/nginx"
networks:
    kolschnet:
        external:
            name: kolschnet